WARNING: If you use conda to create environments, your home directory may fill up. Please see our documentation at 
 https://www.wiki.ed.ac.uk/display/ResearchServices/Anaconda for advice.
rmdir: failed to remove '/exports/eddie/scratch/s2062378/data/training': No such file or directory
rmdir: failed to remove '/exports/eddie/scratch/s2062378/data/validation': No such file or directory
rmdir: failed to remove '/exports/eddie/scratch/s2062378/data/testing': No such file or directory
Traceback (most recent call last):
  File "/home/s2062378/Synthetic-Radio-Frequency-Data-Generator/generator.py", line 11, in <module>
    from utils import *
  File "/exports/eddie3_homes_local/s2062378/Synthetic-Radio-Frequency-Data-Generator/utils/__init__.py", line 10, in <module>
    from .test_utils import get_psd
ModuleNotFoundError: No module named 'utils.test_utils'
Traceback (most recent call last):
  File "/home/s2062378/Synthetic-Radio-Frequency-Data-Generator/generator.py", line 11, in <module>
    from utils import *
  File "/exports/eddie3_homes_local/s2062378/Synthetic-Radio-Frequency-Data-Generator/utils/__init__.py", line 10, in <module>
    from .test_utils import get_psd
ModuleNotFoundError: No module named 'utils.test_utils'
Traceback (most recent call last):
  File "/home/s2062378/Synthetic-Radio-Frequency-Data-Generator/generator.py", line 11, in <module>
    from utils import *
  File "/exports/eddie3_homes_local/s2062378/Synthetic-Radio-Frequency-Data-Generator/utils/__init__.py", line 10, in <module>
    from .test_utils import get_psd
ModuleNotFoundError: No module named 'utils.test_utils'
Traceback (most recent call last):
  File "/home/s2062378/Synthetic-Radio-Frequency-Data-Generator/YOLO-Model/main.py", line 17, in <module>
    from dataset_wideband_yolo import WidebandYoloDataset
  File "/exports/eddie3_homes_local/s2062378/Synthetic-Radio-Frequency-Data-Generator/YOLO-Model/dataset_wideband_yolo.py", line 9, in <module>
    from config_wideband_yolo import (
  File "/exports/eddie3_homes_local/s2062378/Synthetic-Radio-Frequency-Data-Generator/YOLO-Model/config_wideband_yolo.py", line 49, in <module>
    calculate_band_margin()
  File "/exports/eddie3_homes_local/s2062378/Synthetic-Radio-Frequency-Data-Generator/YOLO-Model/config_wideband_yolo.py", line 17, in calculate_band_margin
    file_name = os.listdir(os.path.abspath(dataset_directory))[0]
FileNotFoundError: [Errno 2] No such file or directory: '/exports/eddie/scratch/s2062378/data/training'
